/**
 * Every task id, in tour order. The catalog and every language file are
 * typed against this list, so a task cannot exist without its text in all
 * eight languages, and a language file cannot drift from the catalog.
 */
export const TASK_IDS = [
  'sign-up',
  'trust-device',
  'add-passkey',
  'see-session',
  'sign-out-everywhere',
  'first-workspace',
  'create-workspace',
  'switch-workspace',
  'rename-workspace',
  'workspace-settings-screens',
  'delete-workspace',
  'invite-member',
  'pending-seat',
  'accept-invitation',
  'change-role',
  'viewer-limits',
  'revoke-invitation',
  'seat-limit',
  'see-trial',
  'compare-plans',
  'subscribe',
  'trial-banner-gone',
  'view-invoice',
  'billing-portal',
  'upgrade',
  'cancel-resume',
  'seat-price',
  'record-usage',
  'usage-threshold',
  'usage-limit',
  'usage-log',
  'see-balance',
  'spend-credits',
  'credits-low',
  'buy-credits',
  'credit-transactions',
  'feature-off',
  'feature-on',
  'user-feature',
  'permission-matrix',
  'forbidden-action',
  'custom-role',
  'inbox-first-item',
  'send-notification',
  'inbox-live',
  'open-from-email',
  'mark-all-read',
  'notification-preferences',
  'required-event',
  'delivery-log',
  'push-subscribe',
  'push-receive',
  'push-click',
  'mcp-config',
  'mcp-connect',
  'mcp-call',
  'mcp-write',
  'agent-list',
  'llms-txt',
  'webhook-received',
  'sdk-events',
  'switch-language',
  'rtl',
  'dark-mode',
  'export-data',
  'clone-it',
  'delete-account',
] as const;

export type TaskId = (typeof TASK_IDS)[number];
